-- ~/.config/nvim/lua/codebeam/highlights.lua (ora in codebeam.nvim/lua/codebeam/highlights.lua)
local M = {}
local function set_hl(group, fg, bg, style)
    local opts = { fg = fg, bg = bg, bold = style and style.bold, italic = style and style.italic, underline = style and style.underline, reverse = style and style.reverse }
    vim.api.nvim_set_hl(0, group, opts)
end
function M.apply_highlights(colors)
    set_hl("Normal", colors.light_gray, colors.dark_gray)
    set_hl("Comment", colors.lighter_gray, nil, { italic = true })
    set_hl("LineNr", colors.lighter_gray, nil)
    set_hl("EndOfBuffer", colors.lighter_gray, nil)
    set_hl("CursorLine", nil, colors.medium_gray)
    set_hl("CursorLineNr", colors.light_gray, colors.medium_gray, { bold = true })
    set_hl("Visual", nil, colors.subtle_green)
    set_hl("Search", colors.dark_gray, colors.accent_green)
    set_hl("IncSearch", colors.dark_gray, colors.warning_yellow)
    set_hl("Keyword", colors.neutral_purple, nil, { bold = true })
    set_hl("Statement", colors.neutral_purple, nil, { bold = true })
    set_hl("Conditional", colors.neutral_purple)
    set_hl("Repeat", colors.neutral_purple)
    set_hl("Function", colors.neutral_green, nil)
    set_hl("Method", colors.neutral_green)
    set_hl("String", colors.accent_green)
    set_hl("Character", colors.accent_green)
    set_hl("Number", colors.neutral_orange)
    set_hl("Boolean", colors.neutral_orange)
    set_hl("Constant", colors.neutral_orange)
    set_hl("Type", colors.neutral_blue)
    set_hl("Identifier", colors.neutral_blue)
    set_hl("Struct", colors.neutral_blue)
    set_hl("StorageClass", colors.neutral_blue)
    set_hl("Operator", colors.light_gray)
    set_hl("PunctDelimiter", colors.light_gray)
    set_hl("Error", colors.error_red, nil)
    set_hl("ErrorMsg", colors.error_red, nil, { bold = true })
    set_hl("Warning", colors.warning_yellow, nil)
    set_hl("WarningMsg", colors.warning_yellow, nil, { bold = true })
    set_hl("Todo", colors.warning_yellow, nil, { bold = true, underline = true })
    set_hl("DiffAdd", colors.accent_green, nil)
    set_hl("DiffChange", colors.neutral_blue, nil)
    set_hl("DiffDelete", colors.error_red, nil)
    set_hl("DiffText", nil, colors.medium_gray)
    set_hl("Conceal", colors.lighter_gray, nil)
    set_hl("Folded", colors.lighter_gray, colors.medium_gray, { italic = true })
    set_hl("NonText", colors.medium_gray, nil)
    vim.cmd("hi! link Directory Type")
    vim.cmd("hi! link Title Function")
    vim.cmd("hi! link WildMenu Normal")
    vim.cmd("hi! link MatchParen Function")
    vim.cmd("hi! link StatusLine Normal")
    vim.cmd("hi! link StatusLineNC Normal")
    vim.cmd("hi! link TabLine Normal")
    vim.cmd("hi! link TabLineFill Normal")
    vim.cmd("hi! link TabLineSel Statement")
end
return M